//        update  heyang.cbjcjb set sjtbzt=0 where sjtbzt=1;
//        update  heyang.cbjdyz set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtbca set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtnhv set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtcpe set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtnbs set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtcsq set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtndo set sjtbzt=0 where sjtbzt=1;
//        update  heyang.cbjyyx set sjtbzt=0 where sjtbzt=1;
//        update  heyang.cbjdbz set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdgrj set sjtbzt=0 where sjtbzt=1;
//        update  heyang.cbjyqt set sjtbzt=0 where sjtbzt=1;
//        update  heyang.cbjglb set sjtbzt=0 where sjtbzt=1;
//        update  heyang.cbjfpe set sjtbzt=0 where sjtbzt=1;
//        update  heyang.chtcur set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdoprc set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdoscg set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdotso set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdopcr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdofpc set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdompc set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrtcm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrylf set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrwmp set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdopsa set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdobdm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdommr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdopce set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdopgc set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bsigrx set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bsijtx set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdmpwh set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdjkd set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdggm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdgss set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdmsmi set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdmoph set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdmtdp set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdmccm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsimr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsppr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdscap set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsmco set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdscrb set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsbrf set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsodr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsohm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdgws set sjtbzt=0 where sjtbzt=1;
//        update  heyang.tjxwex set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emroem set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emreom set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdstrt set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdsyfj set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrmii set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrtrd set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrito set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdcd set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdrs set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdsb set sjtbzt=0 where sjtbzt=1;
//        update  heyang.bdssyx set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrtfp set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdgsx set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdsn set sjtbzt=0 where sjtbzt=1;
//        update  heyang.tjxtgj set sjtbzt=0 where sjtbzt=1;
//        update  heyang.tjxfzj set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdod set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrcrd set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrps0 set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrssm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdcr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrfcr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrtfr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrsfr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrwrr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrsrd set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdgjw set sjtbzt=0 where sjtbzt=1;
//        update  heyang.jkdgjz set sjtbzt=0 where sjtbzt=1;
//        update  heyang.tjxsys set sjtbzt=0 where sjtbzt=1;
//        update  heyang.tjxpgj set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emraad set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrcin set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrict set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrsea set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdir set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrhpo set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrbtt set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrica set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emroic set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrpif set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrcir set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrhpi set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrhif set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emraer set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrnpr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emriao set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrsnr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrccr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrhvc set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrwss set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrtmr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrdea set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrgnr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrpai set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrisr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emraud set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrnsr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrvsm set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrwfd set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrvdr set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrcso set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrpd0 set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrard set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emraai set sjtbzt=0 where sjtbzt=1;
//        update  heyang.emrbtr set sjtbzt=0 where sjtbzt=1;


//        update huayin.emrylf  set sjtbzt=0;
//        update  huayin.emrwss set sjtbzt=0;
//        update  huayin.emrwrr set sjtbzt=0;
//        update  huayin.emrwmp set sjtbzt=0;
//        update  huayin.emrwfd set sjtbzt=0;
//        update  huayin.emrvsm set sjtbzt=0;
//        update  huayin.emrvdr set sjtbzt=0;
//        update  huayin.emrtmr set sjtbzt=0;
//        update  huayin.emrtfr set sjtbzt=0;
//        update  huayin.emrtfp set sjtbzt=0;
//        update  huayin.emrtcm set sjtbzt=0;
//        update  huayin.emrssm set sjtbzt=0;
//        update  huayin.emrsrd set sjtbzt=0;
//        update  huayin.emrsfr set sjtbzt=0;
//        update  huayin.emrsea set sjtbzt=0;
//        update  huayin.emrps0 set sjtbzt=0;
//        update  huayin.emrpif set sjtbzt=0;
//        update  huayin.emrpd0 set sjtbzt=0;
//        update  huayin.emroic set sjtbzt=0;
//        update  huayin.emroem set sjtbzt=0;
//        update  huayin.emrnpr set sjtbzt=0;
//        update  huayin.emrito set sjtbzt=0;
//        update  huayin.emrisr set sjtbzt=0;
//        update  huayin.emrict set sjtbzt=0;
//        update  huayin.emrica set sjtbzt=0;
//        update  huayin.emriao set sjtbzt=0;
//        update  huayin.emrhif set sjtbzt=0;
//        update  huayin.emrfcr set sjtbzt=0;
//        update  huayin.emreom set sjtbzt=0;
//        update  huayin.emrdsn set sjtbzt=0;
//        update  huayin.emrdsb set sjtbzt=0;
//        update  huayin.emrdrs set sjtbzt=0;
//        update  huayin.emrdod set sjtbzt=0;
//        update  huayin.emrdir set sjtbzt=0;
//        update  huayin.emrdea set sjtbzt=0;
//        update  huayin.emrdcr set sjtbzt=0;
//        update  huayin.emrcso set sjtbzt=0;
//        update  huayin.emrcir set sjtbzt=0;
//        update  huayin.emrcin set sjtbzt=0;
//        update  huayin.emrbtt set sjtbzt=0;
//        update  huayin.emraud set sjtbzt=0;
//        update  huayin.emraer set sjtbzt=0;
//        update  huayin.emraad set sjtbzt=0;

